In [2]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**Iterative Policy Evaluation in Grid-World**
- fix the state transfer prob matrix S
- fix the reward of each grid =-1
- initialize the policy as equiprobable

In [136]:
# initialize v_k
large_vk = np.array(list(range(36))).reshape(6,6)

# initialize policy: [up,down,left,right|s]
policy = np.ones(4)*0.25

# interations 
itera = 100

# action dict
action_row_dict = {'up':-1,'down':1,
                   'left':0,'right':0}
action_col_dict = {'up':0,'down':0,
                   'left':-1,'right':1}

act_row = np.vectorize(lambda x:action_row_dict[x])
act_col = np.vectorize(lambda x:action_col_dict[x])


# acting/updating vk
def act(large_vk,row_m,col_m):
    
    # initial coordinates
    cod = np.meshgrid([1,2,3,4],[1,2,3,4])
    
    row_moving = cod[1] + row_m
    col_moving = cod[0] + col_m
    
    added_value = large_vk[row_moving,col_moving]
    large_vk[cod[1],cod[0]] += added_value 
    
    return large_vk,row_m,col_m,added_value

# Full Backup DP
action = np.random.choice(a = ['up','down','left','right'], 
                          p = policy,
                          size=(4,4))

a,b,c,d=act(large_vk,act_row(action),act_col(action))

In [137]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6, 15, 22, 24, 19, 11],
       [12, 25, 34, 29, 31, 17],
       [18, 37, 41, 48, 50, 23],
       [24, 49, 58, 60, 57, 29],
       [30, 31, 32, 33, 34, 35]])

In [139]:
np.array(list(range(36))).reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [140]:
action

array([['right', 'down', 'down', 'left'],
       ['left', 'down', 'left', 'left'],
       ['left', 'right', 'down', 'down'],
       ['left', 'down', 'down', 'right']], dtype='<U5')

In [115]:
large[cod[1],cod[0]]

array([[ 7,  8,  9, 10],
       [13, 14, 15, 16],
       [19, 20, 21, 22],
       [25, 26, 27, 28]])

In [86]:
vec_act = np.vectorize(Row_Act)

In [87]:
actions = np.random.choice(a = ['up','down','left','right'],size=(4,4),p = policy)

In [88]:
actions.flatten().reshape(4,4)

array([['left', 'down', 'right', 'right'],
       ['up', 'up', 'right', 'left'],
       ['down', 'down', 'up', 'left'],
       ['right', 'up', 'down', 'up']], dtype='<U5')

In [92]:
a = np.random.randint(0,10,(2,2))

In [96]:
np.meshgrid(a,indexing='xy')

[array([5, 6, 7, 0])]

In [98]:
x = [0,1,2,3]
y = [0,1,2,3]

In [99]:
np.meshgrid(x,y)

[array([[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]),
 array([[0, 0, 0, 0],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])]